project:
  type: website
  output-dir: docs

metadata-files:
  - _sidebar.yml

website:
  navbar:
    background: "#343a40"
    search: true
    left:
      - text: "MLuno"
        file: index.qmd
      - text: "Reference"
        file: reference/

quartodoc:
  package: mluno
  sidebar: _sidebar.yml
  sections:
    - title: Data Utilities
      desc: Functions to simulate and split data.
      package: mluno.data
      contents:
        - make_line_data
        - make_sine_data
        - split_data

    - title: Regressors
      desc: Regression models.
      package: mluno.regressors
      contents:
        - KNNRegressor
        - LinearRegressor

    - title: Conformal Prediction
      desc: Conformal prediction methods.
      package: mluno.conformal
      contents:
        - ConformalPredictor

    - title: Metrics
      desc: Evaluation metrics.
      package: mluno.metrics
      contents:
        - rmse
        - mae
        - coverage
        - sharpness

    - title: Plotting
      desc: Visualization functions.
      package: mluno.plot
      contents:
        - plot_predictions
